services:
  - type: web
    name: mini-ecommerce-backend
    runtime: python
    buildCommand: cd Backend && pip install -r requirements.txt && python manage.py migrate --noinput
    startCommand: cd Backend && gunicorn ecommerce.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
    plan: free

